version: '3.8'

services:
  data_pipeline:
    build:
      context: ./data_pipeline
    container_name: data_pipeline
    volumes:
      - ./data/:/app/data/
    depends_on: []
    restart: on-failure
    command: ["python", "pipeline.py"]

  ml_pipeline:
    build:
      context: ./ml_pipeline
    container_name: ml_pipeline
    volumes:
      - ./model/:/app/model/
      - ./data/:/app/data/
    depends_on:
      - data_pipeline
    restart: on-failure
    command: ["python", "train.py"]

  app:
    build:
      context: ./app
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./model/:/app/model/
    depends_on:
      - ml_pipeline
    restart: always
