version: '3.8'

services:
  data_pipeline:
    build:
      context: ./data_pipeline
    container_name: data_pipeline
    volumes:
      - ./data/:/app/data/
    depends_on: []
    restart: on-failure
    command: ["python", "pipeline.py"]

  ml_pipeline:
    build:
      context: ./ml_pipeline
    container_name: ml_pipeline
    volumes:
      - ./model/:/app/model/
      - ./data/:/app/data/
    depends_on:
      - data_pipeline
    restart: on-failure
    command: ["python", "train.py"]

  app:
    build:
      context: ./app
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./model/:/app/model/
      - ./ml_pipeline/:/app/ml_pipeline/
      - ./data/:/app/data/
    depends_on:
      - ml_pipeline
    restart: always

  metrics_exporter:
    build: ./system-metric-exporter
    container_name: metrics_exporter
    restart: always
    ports:
      - "18000:18000"
    volumes:
      - proc:/host_proc:ro
      - dev:/host_dev:ro
    environment:
      - PROC_PATH=/host_proc
    privileged: true
    network_mode: host 
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped


volumes:
  grafana-storage:
  proc:
    driver: local
  dev:
    driver: local