global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'metrics_exporter'
    static_configs:
      - targets: ['metrics_exporter:18000']

  - job_name: 'backend_app'
    static_configs:
      - targets: ['backend_app:8000']
